/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'submitted' : IDL.Null,
  'reviewed' : IDL.Null,
  'draft' : IDL.Null,
});
export const KategoriKegiatan = IDL.Variant({
  'penegakPandega' : IDL.Null,
  'siaga' : IDL.Null,
  'anggotaDewasa' : IDL.Null,
  'penggalang' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const JudgingDocument = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'updatedAt' : IDL.Int,
});
export const Kegiatan = IDL.Record({
  'id' : IDL.Text,
  'frekuensi' : IDL.Nat,
  'kategori' : KategoriKegiatan,
  'bukti' : IDL.Vec(JudgingDocument),
  'namaKegiatan' : IDL.Text,
});
export const Potensi = IDL.Record({
  'satuanKaryaAktif' : IDL.Vec(IDL.Text),
  'karyawanSekretariat' : IDL.Nat,
  'gudep' : IDL.Record({ 'putera' : IDL.Nat, 'puteri' : IDL.Nat }),
  'anggotaDewasa' : IDL.Record({
    'pelatih' : IDL.Nat,
    'andalan' : IDL.Nat,
    'pembina' : IDL.Nat,
  }),
  'anggotaMuda' : IDL.Record({
    'siagaPutera' : IDL.Nat,
    'siagaPuteri' : IDL.Nat,
    'penegakPutera' : IDL.Nat,
    'penegakPuteri' : IDL.Nat,
    'pandegaPutera' : IDL.Nat,
    'pandegaPuteri' : IDL.Nat,
    'penggalangPutera' : IDL.Nat,
    'penggalangPuteri' : IDL.Nat,
  }),
  'satgasPramukaPeduli' : IDL.Nat,
});
export const Rekap = IDL.Record({
  'skorPotensi' : IDL.Nat,
  'skorKegiatan' : IDL.Nat,
  'skorProfil' : IDL.Nat,
  'skorTotal' : IDL.Nat,
});
export const Profile = IDL.Record({
  'sosialMedia' : IDL.Text,
  'statusBumiPerkemahan' : IDL.Text,
  'noSKTerakhir' : IDL.Text,
  'masaBakti' : IDL.Tuple(IDL.Nat, IDL.Nat),
  'alamat' : IDL.Text,
  'sekretariat' : IDL.Variant({
    'hakGunaPakai' : IDL.Null,
    'milikSendiri' : IDL.Null,
    'tidakPunya' : IDL.Null,
  }),
  'email' : IDL.Text,
  'namaKwarran' : IDL.Text,
  'bumiPerkemahan' : IDL.Bool,
  'ketua' : IDL.Text,
});
export const KwartirRanting = IDL.Record({
  'id' : IDL.Text,
  'status' : Status,
  'kegiatan' : IDL.Vec(Kegiatan),
  'owner' : IDL.Principal,
  'potensi' : Potensi,
  'rekapan' : Rekap,
  'profile' : Profile,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'kwarranName' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdminPembantu' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateKwartirRanting' : IDL.Func([KwartirRanting], [], []),
  'getAllSortedByScore' : IDL.Func([], [IDL.Vec(KwartirRanting)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocument' : IDL.Func([IDL.Text], [JudgingDocument], ['query']),
  'getRecord' : IDL.Func([IDL.Principal], [KwartirRanting], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdminPembantu' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAdminPembantu' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitKwartirRanting' : IDL.Func([KwartirRanting], [], []),
  'uploadDocument' : IDL.Func([JudgingDocument], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'submitted' : IDL.Null,
    'reviewed' : IDL.Null,
    'draft' : IDL.Null,
  });
  const KategoriKegiatan = IDL.Variant({
    'penegakPandega' : IDL.Null,
    'siaga' : IDL.Null,
    'anggotaDewasa' : IDL.Null,
    'penggalang' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const JudgingDocument = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'updatedAt' : IDL.Int,
  });
  const Kegiatan = IDL.Record({
    'id' : IDL.Text,
    'frekuensi' : IDL.Nat,
    'kategori' : KategoriKegiatan,
    'bukti' : IDL.Vec(JudgingDocument),
    'namaKegiatan' : IDL.Text,
  });
  const Potensi = IDL.Record({
    'satuanKaryaAktif' : IDL.Vec(IDL.Text),
    'karyawanSekretariat' : IDL.Nat,
    'gudep' : IDL.Record({ 'putera' : IDL.Nat, 'puteri' : IDL.Nat }),
    'anggotaDewasa' : IDL.Record({
      'pelatih' : IDL.Nat,
      'andalan' : IDL.Nat,
      'pembina' : IDL.Nat,
    }),
    'anggotaMuda' : IDL.Record({
      'siagaPutera' : IDL.Nat,
      'siagaPuteri' : IDL.Nat,
      'penegakPutera' : IDL.Nat,
      'penegakPuteri' : IDL.Nat,
      'pandegaPutera' : IDL.Nat,
      'pandegaPuteri' : IDL.Nat,
      'penggalangPutera' : IDL.Nat,
      'penggalangPuteri' : IDL.Nat,
    }),
    'satgasPramukaPeduli' : IDL.Nat,
  });
  const Rekap = IDL.Record({
    'skorPotensi' : IDL.Nat,
    'skorKegiatan' : IDL.Nat,
    'skorProfil' : IDL.Nat,
    'skorTotal' : IDL.Nat,
  });
  const Profile = IDL.Record({
    'sosialMedia' : IDL.Text,
    'statusBumiPerkemahan' : IDL.Text,
    'noSKTerakhir' : IDL.Text,
    'masaBakti' : IDL.Tuple(IDL.Nat, IDL.Nat),
    'alamat' : IDL.Text,
    'sekretariat' : IDL.Variant({
      'hakGunaPakai' : IDL.Null,
      'milikSendiri' : IDL.Null,
      'tidakPunya' : IDL.Null,
    }),
    'email' : IDL.Text,
    'namaKwarran' : IDL.Text,
    'bumiPerkemahan' : IDL.Bool,
    'ketua' : IDL.Text,
  });
  const KwartirRanting = IDL.Record({
    'id' : IDL.Text,
    'status' : Status,
    'kegiatan' : IDL.Vec(Kegiatan),
    'owner' : IDL.Principal,
    'potensi' : Potensi,
    'rekapan' : Rekap,
    'profile' : Profile,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'kwarranName' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdminPembantu' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateKwartirRanting' : IDL.Func([KwartirRanting], [], []),
    'getAllSortedByScore' : IDL.Func([], [IDL.Vec(KwartirRanting)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocument' : IDL.Func([IDL.Text], [JudgingDocument], ['query']),
    'getRecord' : IDL.Func([IDL.Principal], [KwartirRanting], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdminPembantu' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAdminPembantu' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitKwartirRanting' : IDL.Func([KwartirRanting], [], []),
    'uploadDocument' : IDL.Func([JudgingDocument], [], []),
  });
};

export const init = ({ IDL }) => { return []; };