/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface JudgingDocument {
  'id' : string,
  'owner' : Principal,
  'blob' : ExternalBlob,
  'name' : string,
  'createdAt' : bigint,
  'updatedAt' : bigint,
}
export type KategoriKegiatan = { 'penegakPandega' : null } |
  { 'siaga' : null } |
  { 'anggotaDewasa' : null } |
  { 'penggalang' : null };
export interface Kegiatan {
  'id' : string,
  'frekuensi' : bigint,
  'kategori' : KategoriKegiatan,
  'bukti' : Array<JudgingDocument>,
  'namaKegiatan' : string,
}
export interface KwartirRanting {
  'id' : string,
  'status' : Status,
  'kegiatan' : Array<Kegiatan>,
  'owner' : Principal,
  'potensi' : Potensi,
  'rekapan' : Rekap,
  'profile' : Profile,
}
export interface Potensi {
  'satuanKaryaAktif' : Array<string>,
  'karyawanSekretariat' : bigint,
  'gudep' : { 'putera' : bigint, 'puteri' : bigint },
  'anggotaDewasa' : {
    'pelatih' : bigint,
    'andalan' : bigint,
    'pembina' : bigint,
  },
  'anggotaMuda' : {
    'siagaPutera' : bigint,
    'siagaPuteri' : bigint,
    'penegakPutera' : bigint,
    'penegakPuteri' : bigint,
    'pandegaPutera' : bigint,
    'pandegaPuteri' : bigint,
    'penggalangPutera' : bigint,
    'penggalangPuteri' : bigint,
  },
  'satgasPramukaPeduli' : bigint,
}
export interface Profile {
  'sosialMedia' : string,
  'statusBumiPerkemahan' : string,
  'noSKTerakhir' : string,
  'masaBakti' : [bigint, bigint],
  'alamat' : string,
  'sekretariat' : { 'hakGunaPakai' : null } |
    { 'milikSendiri' : null } |
    { 'tidakPunya' : null },
  'email' : string,
  'namaKwarran' : string,
  'bumiPerkemahan' : boolean,
  'ketua' : string,
}
export interface Rekap {
  'skorPotensi' : bigint,
  'skorKegiatan' : bigint,
  'skorProfil' : bigint,
  'skorTotal' : bigint,
}
export type Status = { 'submitted' : null } |
  { 'reviewed' : null } |
  { 'draft' : null };
export interface UserProfile { 'name' : string, 'kwarranName' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateKwartirRanting' : ActorMethod<[KwartirRanting], undefined>,
  'getAllSortedByScore' : ActorMethod<[], Array<KwartirRanting>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocument' : ActorMethod<[string], JudgingDocument>,
  'getRecord' : ActorMethod<[Principal], KwartirRanting>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitKwartirRanting' : ActorMethod<[KwartirRanting], undefined>,
  'uploadDocument' : ActorMethod<[JudgingDocument], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];