/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Rekap {
    skorPotensi: bigint;
    skorKegiatan: bigint;
    skorProfil: bigint;
    skorTotal: bigint;
}
export interface Potensi {
    satuanKaryaAktif: Array<string>;
    karyawanSekretariat: bigint;
    gudep: {
        putera: bigint;
        puteri: bigint;
    };
    anggotaDewasa: {
        pelatih: bigint;
        andalan: bigint;
        pembina: bigint;
    };
    anggotaMuda: {
        siagaPutera: bigint;
        siagaPuteri: bigint;
        penegakPutera: bigint;
        penegakPuteri: bigint;
        pandegaPutera: bigint;
        pandegaPuteri: bigint;
        penggalangPutera: bigint;
        penggalangPuteri: bigint;
    };
    satgasPramukaPeduli: bigint;
}
export interface Kegiatan {
    id: string;
    frekuensi: bigint;
    kategori: KategoriKegiatan;
    bukti: Array<JudgingDocument>;
    namaKegiatan: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface KwartirRanting {
    id: string;
    status: Status;
    kegiatan: Array<Kegiatan>;
    owner: Principal;
    potensi: Potensi;
    rekapan: Rekap;
    profile: Profile;
}
export interface JudgingDocument {
    id: string;
    owner: Principal;
    blob: ExternalBlob;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
}
export interface Profile {
    sosialMedia: string;
    statusBumiPerkemahan: string;
    noSKTerakhir: string;
    masaBakti: [bigint, bigint];
    alamat: string;
    sekretariat: Variant_hakGunaPakai_milikSendiri_tidakPunya;
    email: string;
    namaKwarran: string;
    bumiPerkemahan: boolean;
    ketua: string;
}
export interface UserProfile {
    name: string;
    kwarranName?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum KategoriKegiatan {
    penegakPandega = "penegakPandega",
    siaga = "siaga",
    anggotaDewasa = "anggotaDewasa",
    penggalang = "penggalang"
}
export enum Status {
    submitted = "submitted",
    reviewed = "reviewed",
    draft = "draft"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_hakGunaPakai_milikSendiri_tidakPunya {
    hakGunaPakai = "hakGunaPakai",
    milikSendiri = "milikSendiri",
    tidakPunya = "tidakPunya"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAdminPembantu(principal: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createOrUpdateKwartirRanting(record: KwartirRanting): Promise<void>;
    getAllSortedByScore(): Promise<Array<KwartirRanting>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDocument(documentId: string): Promise<JudgingDocument>;
    getRecord(kwarranId: Principal): Promise<KwartirRanting>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerAdminPembantu(): Promise<boolean>;
    removeAdminPembantu(principal: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitKwartirRanting(record: KwartirRanting): Promise<void>;
    uploadDocument(document: JudgingDocument): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, JudgingDocument as _JudgingDocument, KategoriKegiatan as _KategoriKegiatan, Kegiatan as _Kegiatan, KwartirRanting as _KwartirRanting, Potensi as _Potensi, Profile as _Profile, Rekap as _Rekap, Status as _Status, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAdminPembantu(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdminPembantu(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdminPembantu(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrUpdateKwartirRanting(arg0: KwartirRanting): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateKwartirRanting(await to_candid_KwartirRanting_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateKwartirRanting(await to_candid_KwartirRanting_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllSortedByScore(): Promise<Array<KwartirRanting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSortedByScore();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSortedByScore();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocument(arg0: string): Promise<JudgingDocument> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocument(arg0);
                return from_candid_JudgingDocument_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocument(arg0);
            return from_candid_JudgingDocument_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecord(arg0: Principal): Promise<KwartirRanting> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecord(arg0);
                return from_candid_KwartirRanting_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecord(arg0);
            return from_candid_KwartirRanting_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerAdminPembantu(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdminPembantu();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdminPembantu();
            return result;
        }
    }
    async removeAdminPembantu(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdminPembantu(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdminPembantu(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitKwartirRanting(arg0: KwartirRanting): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitKwartirRanting(await to_candid_KwartirRanting_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitKwartirRanting(await to_candid_KwartirRanting_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async uploadDocument(arg0: JudgingDocument): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadDocument(await to_candid_JudgingDocument_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadDocument(await to_candid_JudgingDocument_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_JudgingDocument_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JudgingDocument): Promise<JudgingDocument> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_KategoriKegiatan_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KategoriKegiatan): KategoriKegiatan {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_Kegiatan_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Kegiatan): Promise<Kegiatan> {
    return await from_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_KwartirRanting_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _KwartirRanting): Promise<KwartirRanting> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Profile_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Profile): Profile {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n44(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Status;
    kegiatan: Array<_Kegiatan>;
    owner: Principal;
    potensi: _Potensi;
    rekapan: _Rekap;
    profile: _Profile;
}): Promise<{
    id: string;
    status: Status;
    kegiatan: Array<Kegiatan>;
    owner: Principal;
    potensi: Potensi;
    rekapan: Rekap;
    profile: Profile;
}> {
    return {
        id: value.id,
        status: from_candid_Status_n29(_uploadFile, _downloadFile, value.status),
        kegiatan: await from_candid_vec_n31(_uploadFile, _downloadFile, value.kegiatan),
        owner: value.owner,
        potensi: value.potensi,
        rekapan: value.rekapan,
        profile: from_candid_Profile_n40(_uploadFile, _downloadFile, value.profile)
    };
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    frekuensi: bigint;
    kategori: _KategoriKegiatan;
    bukti: Array<_JudgingDocument>;
    namaKegiatan: string;
}): Promise<{
    id: string;
    frekuensi: bigint;
    kategori: KategoriKegiatan;
    bukti: Array<JudgingDocument>;
    namaKegiatan: string;
}> {
    return {
        id: value.id,
        frekuensi: value.frekuensi,
        kategori: from_candid_KategoriKegiatan_n34(_uploadFile, _downloadFile, value.kategori),
        bukti: await from_candid_vec_n36(_uploadFile, _downloadFile, value.bukti),
        namaKegiatan: value.namaKegiatan
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    blob: _ExternalBlob;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
}): Promise<{
    id: string;
    owner: Principal;
    blob: ExternalBlob;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
}> {
    return {
        id: value.id,
        owner: value.owner,
        blob: await from_candid_ExternalBlob_n39(_uploadFile, _downloadFile, value.blob),
        name: value.name,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sosialMedia: string;
    statusBumiPerkemahan: string;
    noSKTerakhir: string;
    masaBakti: [bigint, bigint];
    alamat: string;
    sekretariat: {
        hakGunaPakai: null;
    } | {
        milikSendiri: null;
    } | {
        tidakPunya: null;
    };
    email: string;
    namaKwarran: string;
    bumiPerkemahan: boolean;
    ketua: string;
}): {
    sosialMedia: string;
    statusBumiPerkemahan: string;
    noSKTerakhir: string;
    masaBakti: [bigint, bigint];
    alamat: string;
    sekretariat: Variant_hakGunaPakai_milikSendiri_tidakPunya;
    email: string;
    namaKwarran: string;
    bumiPerkemahan: boolean;
    ketua: string;
} {
    return {
        sosialMedia: value.sosialMedia,
        statusBumiPerkemahan: value.statusBumiPerkemahan,
        noSKTerakhir: value.noSKTerakhir,
        masaBakti: value.masaBakti,
        alamat: value.alamat,
        sekretariat: from_candid_variant_n42(_uploadFile, _downloadFile, value.sekretariat),
        email: value.email,
        namaKwarran: value.namaKwarran,
        bumiPerkemahan: value.bumiPerkemahan,
        ketua: value.ketua
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    kwarranName: [] | [string];
}): {
    name: string;
    kwarranName?: string;
} {
    return {
        name: value.name,
        kwarranName: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.kwarranName))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    reviewed: null;
} | {
    draft: null;
}): Status {
    return "submitted" in value ? Status.submitted : "reviewed" in value ? Status.reviewed : "draft" in value ? Status.draft : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    penegakPandega: null;
} | {
    siaga: null;
} | {
    anggotaDewasa: null;
} | {
    penggalang: null;
}): KategoriKegiatan {
    return "penegakPandega" in value ? KategoriKegiatan.penegakPandega : "siaga" in value ? KategoriKegiatan.siaga : "anggotaDewasa" in value ? KategoriKegiatan.anggotaDewasa : "penggalang" in value ? KategoriKegiatan.penggalang : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hakGunaPakai: null;
} | {
    milikSendiri: null;
} | {
    tidakPunya: null;
}): Variant_hakGunaPakai_milikSendiri_tidakPunya {
    return "hakGunaPakai" in value ? Variant_hakGunaPakai_milikSendiri_tidakPunya.hakGunaPakai : "milikSendiri" in value ? Variant_hakGunaPakai_milikSendiri_tidakPunya.milikSendiri : "tidakPunya" in value ? Variant_hakGunaPakai_milikSendiri_tidakPunya.tidakPunya : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_KwartirRanting>): Promise<Array<KwartirRanting>> {
    return await Promise.all(value.map(async (x)=>await from_candid_KwartirRanting_n27(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Kegiatan>): Promise<Array<Kegiatan>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Kegiatan_n32(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JudgingDocument>): Promise<Array<JudgingDocument>> {
    return await Promise.all(value.map(async (x)=>await from_candid_JudgingDocument_n37(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_JudgingDocument_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JudgingDocument): Promise<_JudgingDocument> {
    return await to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_KategoriKegiatan_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KategoriKegiatan): _KategoriKegiatan {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
async function to_candid_Kegiatan_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Kegiatan): Promise<_Kegiatan> {
    return await to_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_KwartirRanting_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KwartirRanting): Promise<_KwartirRanting> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Profile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Profile): _Profile {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: Status;
    kegiatan: Array<Kegiatan>;
    owner: Principal;
    potensi: Potensi;
    rekapan: Rekap;
    profile: Profile;
}): Promise<{
    id: string;
    status: _Status;
    kegiatan: Array<_Kegiatan>;
    owner: Principal;
    potensi: _Potensi;
    rekapan: _Rekap;
    profile: _Profile;
}> {
    return {
        id: value.id,
        status: to_candid_Status_n12(_uploadFile, _downloadFile, value.status),
        kegiatan: await to_candid_vec_n14(_uploadFile, _downloadFile, value.kegiatan),
        owner: value.owner,
        potensi: value.potensi,
        rekapan: value.rekapan,
        profile: to_candid_Profile_n23(_uploadFile, _downloadFile, value.profile)
    };
}
async function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    frekuensi: bigint;
    kategori: KategoriKegiatan;
    bukti: Array<JudgingDocument>;
    namaKegiatan: string;
}): Promise<{
    id: string;
    frekuensi: bigint;
    kategori: _KategoriKegiatan;
    bukti: Array<_JudgingDocument>;
    namaKegiatan: string;
}> {
    return {
        id: value.id,
        frekuensi: value.frekuensi,
        kategori: to_candid_KategoriKegiatan_n17(_uploadFile, _downloadFile, value.kategori),
        bukti: await to_candid_vec_n19(_uploadFile, _downloadFile, value.bukti),
        namaKegiatan: value.namaKegiatan
    };
}
async function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    blob: ExternalBlob;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
}): Promise<{
    id: string;
    owner: Principal;
    blob: _ExternalBlob;
    name: string;
    createdAt: bigint;
    updatedAt: bigint;
}> {
    return {
        id: value.id,
        owner: value.owner,
        blob: await to_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value.blob),
        name: value.name,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sosialMedia: string;
    statusBumiPerkemahan: string;
    noSKTerakhir: string;
    masaBakti: [bigint, bigint];
    alamat: string;
    sekretariat: Variant_hakGunaPakai_milikSendiri_tidakPunya;
    email: string;
    namaKwarran: string;
    bumiPerkemahan: boolean;
    ketua: string;
}): {
    sosialMedia: string;
    statusBumiPerkemahan: string;
    noSKTerakhir: string;
    masaBakti: [bigint, bigint];
    alamat: string;
    sekretariat: {
        hakGunaPakai: null;
    } | {
        milikSendiri: null;
    } | {
        tidakPunya: null;
    };
    email: string;
    namaKwarran: string;
    bumiPerkemahan: boolean;
    ketua: string;
} {
    return {
        sosialMedia: value.sosialMedia,
        statusBumiPerkemahan: value.statusBumiPerkemahan,
        noSKTerakhir: value.noSKTerakhir,
        masaBakti: value.masaBakti,
        alamat: value.alamat,
        sekretariat: to_candid_variant_n25(_uploadFile, _downloadFile, value.sekretariat),
        email: value.email,
        namaKwarran: value.namaKwarran,
        bumiPerkemahan: value.bumiPerkemahan,
        ketua: value.ketua
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    kwarranName?: string;
}): {
    name: string;
    kwarranName: [] | [string];
} {
    return {
        name: value.name,
        kwarranName: value.kwarranName ? candid_some(value.kwarranName) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    submitted: null;
} | {
    reviewed: null;
} | {
    draft: null;
} {
    return value == Status.submitted ? {
        submitted: null
    } : value == Status.reviewed ? {
        reviewed: null
    } : value == Status.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: KategoriKegiatan): {
    penegakPandega: null;
} | {
    siaga: null;
} | {
    anggotaDewasa: null;
} | {
    penggalang: null;
} {
    return value == KategoriKegiatan.penegakPandega ? {
        penegakPandega: null
    } : value == KategoriKegiatan.siaga ? {
        siaga: null
    } : value == KategoriKegiatan.anggotaDewasa ? {
        anggotaDewasa: null
    } : value == KategoriKegiatan.penggalang ? {
        penggalang: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_hakGunaPakai_milikSendiri_tidakPunya): {
    hakGunaPakai: null;
} | {
    milikSendiri: null;
} | {
    tidakPunya: null;
} {
    return value == Variant_hakGunaPakai_milikSendiri_tidakPunya.hakGunaPakai ? {
        hakGunaPakai: null
    } : value == Variant_hakGunaPakai_milikSendiri_tidakPunya.milikSendiri ? {
        milikSendiri: null
    } : value == Variant_hakGunaPakai_milikSendiri_tidakPunya.tidakPunya ? {
        tidakPunya: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Kegiatan>): Promise<Array<_Kegiatan>> {
    return await Promise.all(value.map(async (x)=>await to_candid_Kegiatan_n15(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<JudgingDocument>): Promise<Array<_JudgingDocument>> {
    return await Promise.all(value.map(async (x)=>await to_candid_JudgingDocument_n20(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
